name: BotBaseMinigames
version: '${version}'
main: gruvexp.bbminigames.Main
api-version: '1.21'
authors: [ Gruve ]
description: Plugin for the BotBows Minigames server
commands:
  menu:
    usage: /menu
    description: Used to access the game menu
    aliases:
      - /join
      - /play
  settings:
    usage: /settings
    description: Used when you want to view or change the settings of the game
  botbows:
    usage: /botbows
    aliases:
      - /bb
      - /botbase
    description: Commands related to the BotBows game
  test:
    usage: /test
    description: Used for debugging
